jobs:
  up:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      run: 'git fetch --tags --force && \

        latest=$(git tag --sort=creatordate | tail -1) && \

        sed -E -i "s/<version>[^<]+/<version>${latest}/g" README.md && \

        sed -E -i "s/org.cactoos:cactoos:.+/org.cactoos:cactoos::${latest}/g" README.md'
    - continue-on-error: true
      uses: peter-evans/create-pull-request@v6
      with:
        assignees: yegor256
        base: master
        branch: up
        commit-message: new version in README
        delete-branch: true
        title: New version in README
name: up
on:
  repository_dispatch:
    types: trigger-ga___up.yml
